### ISSUE TITLE
Add FindSDL2_mixer.cmake ?

### ISSUE THREAD

**Issue by jgvictores** [tcbrindle/sdl2-cmake-scripts#8]
Such as: https://github.com/ksterker/adonthell/blob/master/config/FindSDL2_mixer.cmake

**Comment by tcbrindle** [comment]
I'm happy to include CMake files for the other SDL libraries, such as `SDL2_mixer`, `gfx` and `net`, if people would find them useful.

However, if they're added then I'd like them to match as closely as possible to the existing `image` and `ttf` files (i.e. more-or-less a copy and paste with the variable names/paths changed). This would make it easier to keep fixes consistent between the various files.
